version: 2

defaults: &defaults
  working_directory: ~/project/runner
  docker:
    - image: labeldock/circleci-node:8.11

jobs:
  initialize:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: npm module
          command: npm install
      - persist_to_workspace:
          root: ~/project
          paths:
            - runner

  test-basic:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: TEST
          command: npm run test:basic

  test-verbose:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: TEST
          command: npm run test:verbose
  
  test-multi:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: TEST
          command: npm run test:multi

workflows:
  version: 2
  task:
    jobs:
      - initialize
      - test-basic:
          requires:
            - initialize
      - test-verbose:
          requires:
            - initialize
      - test-multi:
          requires:
            - initialize
